import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-full flex items-center gap-6 px-6 py-4 border-b mb-8">
          <Link href="/" className="text-lg font-bold text-blue-700">NovelPlanet</Link>
          <Link href="/history" className="text-sm text-blue-600 hover:underline">
            📚 History
          </Link>
          <Link href="/search" className="text-sm text-blue-600 hover:underline">
            🔍 Search
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
